x = int(input("Enter the value of x:"))
y = int(input("Enter the value of y:"))
z = int(input("Enter the value of z:"))
output=x+y+z
print('x+y+z =',x+y+z)
output=x-y-z
print('x-y-z =',x-y-z)
output=(x*y)*z
print('(x*y)*z =',(x*y)*z)
output=(x**y)**z
print('(x**y)**z =',(x**y)**z)
output=(x/y)/z
print('(x/y)/z =',(x/y)/z)
output=(x//y)//z
print('(x//y)//z =',(x//y)//z)
output=(x%y)%z
print('(x%y)%z =',(x%y)%z)
